SET(CMAKE_SYSTEM_NAME Linux)

SET(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc.exe)
SET(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++.exe)

SET(CMAKE_FIND_ROOT_PATH "C:/Tools/SysGCC/raspberry/")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
